name: Flutter Test
on:
  push:
    branches:
      - master
      - main
      - develop
  pull_request:
    branches:
      - master
      - main
      - develop
jobs:
  test:
    name: Flutter Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.3'
          cache: true
      - name: Install packages
        run: |
          flutter pub get
      - name: Linter
        run: |
          flutter analyze
      - name: Test
        run: |
          bash ./scripts/test.sh
      - name: Report
        uses: dorny/test-reporter@v1
        with:
          name: 'Test Report'
          path: 'temp_report.log'
          reporter: 'flutter-json'
          fail-on-error: 'false'
      - name: Code Coverage Report
        uses: romeovs/lcov-reporter-action@v0.3.1