name: Flutter Integration Test

on: workflow_dispatch


jobs:
  integration_test_ios:
    name: IntegrationTest(iOS)
    runs-on: macos-latest
    timeout-minutes: 60
    strategy:
      matrix:
        device:
          - "iPhone 8"
          - "iPhone 13 mini"
          - "iPhone 13 Pro Max"
          - "iPhone 13"
          - "iPhone 13 Pro"
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: boot simulator
        timeout-minutes: 10
        run: |
          bash ./.github/workflows/ios/simulator_start.sh "${{ matrix.device }}"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.3'
          cache: true
      - name: run integration test
        run: |
          bash ./.github/workflows/ios/integration_test.sh "${{ matrix.device }}"

  integration_test_android:
    name: IntegrationTest(Android)
    runs-on: macos-latest
    timeout-minutes: 60
    strategy:
      matrix:
        include:
          - api-level: 18
            arch: x86
            target: default
          - api-level: 31
            arch: x86_64
            target: default

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '11'
          cache: 'gradle'
      - uses: gradle/gradle-build-action@v2
      - name: AVD cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}-${{ matrix.target }}-${{ matrix.arch }}

      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: ${{ matrix.arch }}
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.3'
          cache: true
      - name: run integration test
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: ${{ matrix.arch }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: |
            bash ./scripts/integration_test.sh "emulator-5554"

